version: '3'
services:
  headless-shell:
    image: chromedp/headless-shell:latest
    restart: always
    ports:
      - 9222:9222
  chat.openai.com:
    image: caddy:latest
    restart: always
    ports:
      - 8290:80
      - 8443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
  busybox:
    image: busybox
    command: tail -f /dev/null
  # xyhelper-arkose:
  #   image: xyhelper/xyhelper-arkose:latest
  #   restart: always
  #   network_mode: "host"
  #   # ports:
  #   #   - 8199:8199
  #   environment:
  #     - BROWSERURL=http://127.0.0.1:9222
