version: '3'
services:
  headless-shell:
    image: chromedp/headless-shell:latest
    restart: always
    command: ["--ignore-certificate-errors"]
    ports:
      - 127.0.0.1:9222:9222
  chat.openai.com:
    image: caddy:latest
    restart: always
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
  xyhelper-arkose:
    image: xyhelper/xyhelper-arkose:latest
    restart: always
    network_mode: "host"
    environment:
      - PORT=8199
      - BROWSERURL=http://127.0.0.1:9222
      - PAYLOAD_EXPIRE=10800
      - TOKEN_EXPIRE=1200
      - INTERVAL=0
