version: '3'
services:
  chat.openai.com:
    image: xyhelper/xyhelper-arkose:latest
    restart: always
    ports:
      - 8199:80
    environment:
      - PORT=80
  chrome:
    image: kasmweb/chrome:1.10.0
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=xyhelper
      - URL=http://chat.openai.com
      - APP_ARGS=--ignore-certificate-errors
    shm_size: 512m

