version: '3'
services:
  chat.openai.com:
    image: xyhelper/xyhelper-arkose:latest
    restart: always
    # network_mode: "host"
    ports:
      - 8199:80
    volumes:
      - $PWD/config.prod.yaml:/app/config.yaml
    environment:
      - PORT=80
  chrome:
    image: kasmweb/chrome:1.10.0
    ports:
      - "6901:6901"
    environment:
      - VNC_PW=xyhelper
      - URL=http://chat.openai.com
    shm_size: 512m

